
import { NextResponse } from "next/server";
import { propertyData } from "@/app/types/property/propertyData";

type PropertyType = 'Casa' | 'Departamento' | 'Lote' | 'Dúplex' | 'Finca' | 'Cochera' | 'Hotel' | 'PH';
type OperationType = 'Venta' | 'Alquiler';
type Zone = 'Capital' | 'Godoy Cruz' | 'Guaymallén' | 'Las Heras' | 'Luján de Cuyo' | 'Maipú' | 'El Challao' | 'San Carlos' | 'San Martín' | 'Santa Rosa' | 'Junín' | 'San Rafael' | 'Tunuyán';

interface Property {
  id: number; title: string; address: string; zone: Zone;
  type: PropertyType; operation: OperationType;
  price: number; currency: 'USD' | 'ARS';
  bedrooms?: number; bathrooms?: number;
  m2Total?: number; m2Cubiertos?: number;
  garage?: boolean; featured: boolean;
  description: string; images: string[];
}

const categoryMap: Record<PropertyType, string> = {
  Casa: 'house', Departamento: 'apartment', Lote: 'shop', Dúplex: 'villa',
  Finca: 'warehouse', Cochera: 'shop', Hotel: 'office', PH: 'office',
};

const categoryImgMap: Record<string, string> = {
  house: '/images/property_option/house.svg',
  apartment: '/images/property_option/apartment.svg',
  villa: '/images/property_option/villa.svg',
  office: '/images/property_option/office.svg',
  shop: '/images/property_option/shop.svg',
  warehouse: '/images/property_option/warehouse.svg',
};

function formatPrice(price: number, currency: 'USD' | 'ARS'): string {
  if (currency === 'USD') return `USD ${price.toLocaleString('es-AR')}`;
  return `$ ${price.toLocaleString('es-AR')}`;
}

function toSlug(title: string): string {
  return title.toLowerCase()
    .normalize('NFD').replace(/[\u0300-\u036f]/g, '')
    .replace(/\s+/g, '-').replace(/[^a-z0-9-]/g, '').replace(/-+/g, '-');
}

const modicaProperties: Property[] = [
  { id: 1, title: 'Casa Martín Zapata 458', address: 'Martín Zapata 458, Capital', zone: 'Capital', type: 'Casa', operation: 'Venta', price: 180000, currency: 'USD', bedrooms: 3, bathrooms: 2, m2Total: 280, m2Cubiertos: 180, garage: true, featured: true, description: 'Hermosa casa en zona privilegiada de Capital. Amplio terreno con jardín, espacios luminosos y excelente distribución. Ideal para familia. A pasos de todos los servicios.', images: ['/properties/1/IMG_6502 - Lorena Gutierrez.jpeg'] },
  { id: 2, title: 'Casa Santa María de Oro', address: 'Santa María de Oro, Capital', zone: 'Capital', type: 'Casa', operation: 'Venta', price: 220000, currency: 'USD', bedrooms: 4, bathrooms: 2, m2Total: 350, m2Cubiertos: 220, garage: true, featured: true, description: 'Espaciosa casa familiar en excelente ubicación. Amplias habitaciones, living comedor, cocina equipada, patio trasero y cochera. Zona muy tranquila y segura.', images: ['/properties/2/00dfab64-3610-4e25-af12-bb56571c956c.jpg'] },
  { id: 3, title: 'Departamento Ayacucho 380', address: 'Ayacucho 380, Capital', zone: 'Capital', type: 'Departamento', operation: 'Venta', price: 85000, currency: 'USD', bedrooms: 2, bathrooms: 1, m2Cubiertos: 75, garage: false, featured: true, description: 'Moderno departamento en el corazón de Capital. Dos dormitorios, cocina integrada, balcón. Edificio con amenities. Ideal inversión o primera vivienda.', images: ['/properties/3/08b9937f-2e55-479d-a7d8-3348022a5786.jpg'] },
  { id: 4, title: 'Departamento Colón y Chile', address: 'Colón y Chile, Capital', zone: 'Capital', type: 'Departamento', operation: 'Venta', price: 72000, currency: 'USD', bedrooms: 1, bathrooms: 1, m2Cubiertos: 55, garage: false, featured: false, description: 'Luminoso departamento de 1 dormitorio en inmejorable ubicación céntrica. A metros de peatonal Sarmiento, shoppings y transporte público.', images: ['/properties/4/IMG-20250806-WA0007 - Paulo Ponce.jpeg'] },
  { id: 5, title: 'Edificio Villa Carrara', address: 'Villa Carrara, Capital', zone: 'Capital', type: 'Departamento', operation: 'Venta', price: 68000, currency: 'USD', bedrooms: 2, bathrooms: 1, m2Cubiertos: 65, garage: false, featured: false, description: 'Elegante departamento en Edificio Villa Carrara. Dos ambientes amplios, cocina americana, excelentes terminaciones. Edificio moderno con seguridad 24hs.', images: ['/properties/5/WhatsApp Image 2026-02-04 at 18.04.06 (2) - Francisco Andreoni.jpeg'] },
  { id: 6, title: 'Monoambiente Necochea', address: 'Necochea, Capital', zone: 'Capital', type: 'Departamento', operation: 'Venta', price: 42000, currency: 'USD', bedrooms: 0, bathrooms: 1, m2Cubiertos: 32, garage: false, featured: false, description: 'Práctico monoambiente totalmente equipado. Ideal para estudiante o profesional. Excelente renta. Muy bien ubicado en zona céntrica.', images: ['/properties/6/07883189-e82f-405e-8b14-ea477fc665ca.jpg'] },
  { id: 7, title: 'Pasaje Las Glicinas', address: 'Pasaje Las Glicinas, Capital', zone: 'Capital', type: 'Departamento', operation: 'Venta', price: 95000, currency: 'USD', bedrooms: 3, bathrooms: 2, m2Cubiertos: 90, garage: true, featured: false, description: 'Amplio departamento en pasaje tranquilo. Tres dormitorios, dos baños, cochera incluida. Zona residencial con mucho verde.', images: ['/properties/7/03266a21-3234-4238-8fa7-fd6723dde4d0.jpg'] },
  { id: 8, title: 'Cochera 9 de Julio', address: '9 de Julio, Capital', zone: 'Capital', type: 'Cochera', operation: 'Venta', price: 18000, currency: 'USD', featured: false, description: 'Cochera techada en zona céntrica. Excelente para inversión o uso propio. Seguridad y acceso cómodo. A metros del microcentro mendocino.', images: ['/properties/8/entrada cochera.jpg'] },
  { id: 9, title: 'Hotel Cristal', address: 'Capital, Mendoza', zone: 'Capital', type: 'Hotel', operation: 'Venta', price: 950000, currency: 'USD', featured: true, description: 'Importante hotel de categoría en el centro de Mendoza. Excelente oportunidad de inversión en el rubro turístico. Completamente equipado y en funcionamiento.', images: ['/properties/9/1626a202-feea-4333-b196-685a0e944090.jpg'] },
  { id: 10, title: 'Casa Barrio ATSA', address: 'Barrio ATSA, Godoy Cruz', zone: 'Godoy Cruz', type: 'Casa', operation: 'Venta', price: 145000, currency: 'USD', bedrooms: 3, bathrooms: 2, m2Total: 260, m2Cubiertos: 160, garage: true, featured: true, description: 'Hermosa casa en Barrio ATSA, Godoy Cruz. Excelente distribución, jardín con pileta, cochera doble. Zona residencial tranquila y segura con todos los servicios.', images: ['/properties/10/IMG-20250404-WA0016 - Mauri Ponce.jpeg'] },
  { id: 11, title: 'Casa Barrio Bombal', address: 'Barrio Bombal Sur, Godoy Cruz', zone: 'Godoy Cruz', type: 'Casa', operation: 'Venta', price: 140000, currency: 'USD', bedrooms: 4, bathrooms: 3, m2Cubiertos: 200, garage: true, featured: true, description: 'Imponente casa en el prestigioso Barrio Bombal. 4 habitaciones, 3 baños, cochera. Excelente zona residencial de Godoy Cruz. Lista para entrar.', images: ['/properties/11/IMG-20251201-WA0005 - Paulo Ponce.jpeg'] },
  { id: 12, title: 'Casa Mármol 1928', address: 'Mármol 1928, Godoy Cruz', zone: 'Godoy Cruz', type: 'Casa', operation: 'Venta', price: 120000, currency: 'USD', bedrooms: 3, bathrooms: 1, m2Total: 220, m2Cubiertos: 130, garage: false, featured: false, description: 'Casa tradicional en zona consolidada de Godoy Cruz. Amplio patio, tres dormitorios, excelente potencial. Ideal para remodelar a gusto.', images: ['/properties/12/031abf7e-3cb4-4dc1-8536-b86250076dae.jpg'] },
  { id: 13, title: 'Casa Pascual Segura', address: 'Pascual Segura, Godoy Cruz', zone: 'Godoy Cruz', type: 'Casa', operation: 'Venta', price: 135000, currency: 'USD', bedrooms: 3, bathrooms: 2, m2Total: 250, m2Cubiertos: 150, garage: true, featured: false, description: 'Linda casa familiar en Godoy Cruz. Tres dormitorios, living comedor amplio, jardín trasero con galería. Muy bien mantenida. Lista para entrar.', images: ['/properties/13/IMG_3235.JPG'] },
  { id: 14, title: 'Casa República del Líbano - Bombal', address: 'República del Líbano, Bombal, Godoy Cruz', zone: 'Godoy Cruz', type: 'Casa', operation: 'Venta', price: 175000, currency: 'USD', bedrooms: 4, bathrooms: 3, m2Total: 380, m2Cubiertos: 210, garage: true, featured: false, description: 'Lujosa casa en Bombal, Godoy Cruz. Cuatro dormitorios, tres baños, pileta climatizada, quincho y jardín de diseño. La mejor zona del Gran Mendoza.', images: ['/properties/14/0af3f777-235f-44d7-957f-d80ed7ea0bf2.jpg'] },
  { id: 15, title: 'Casa El Trapiche', address: 'El Trapiche, Godoy Cruz', zone: 'Godoy Cruz', type: 'Casa', operation: 'Venta', price: 98000, currency: 'USD', bedrooms: 3, bathrooms: 2, m2Total: 200, m2Cubiertos: 140, garage: true, featured: false, description: 'Cómoda casa en El Trapiche con amplios espacios verdes. Tres dormitorios, dos baños completos, cochera y gran patio para disfrutar.', images: ['/properties/15/f2e2d5b4-29d3-4e4c-a8e7-10add3af06df.jpg'] },
  { id: 16, title: 'Departamento Anatole France', address: 'Anatole France, Godoy Cruz', zone: 'Godoy Cruz', type: 'Departamento', operation: 'Venta', price: 78000, currency: 'USD', bedrooms: 2, bathrooms: 1, m2Cubiertos: 68, garage: false, featured: false, description: 'Moderno departamento de dos dormitorios. Edificio de categoría, amenities, seguridad. Excelente zona residencial de Godoy Cruz.', images: ['/properties/16/0b3b0dfb-3d43-4218-84b9-b5d92326aaa8.jpg'] },
  { id: 17, title: 'Torres El Marqués', address: 'Torres El Marqués, Godoy Cruz', zone: 'Godoy Cruz', type: 'Departamento', operation: 'Venta', price: 92000, currency: 'USD', bedrooms: 2, bathrooms: 2, m2Cubiertos: 85, garage: true, featured: true, description: 'Exclusivo departamento en Torres El Marqués. Dos dormitorios en suite, amenities premium: pileta, gym, SUM. Vistas panorámicas. El más buscado de Godoy Cruz.', images: ['/properties/17/03df5f69-a9c2-46c1-9838-405bbb0c150e.jpg'] },
  { id: 18, title: 'Lote Barrio Privado Palmares', address: 'Barrio Privado Palmares, Godoy Cruz', zone: 'Godoy Cruz', type: 'Lote', operation: 'Venta', price: 65000, currency: 'USD', m2Total: 600, featured: false, description: 'Hermoso lote en barrio privado Palmares. Todas las comodidades de un barrio cerrado: seguridad 24hs, calles pavimentadas, áreas comunes. Ideal construir su hogar.', images: ['/properties/18/IMG-20251129-WA0012 - Paulo Ponce.jpeg'] },
  { id: 19, title: 'Casa Barrio La Barraca', address: 'Barrio La Barraca, Guaymallén', zone: 'Guaymallén', type: 'Casa', operation: 'Venta', price: 110000, currency: 'USD', bedrooms: 3, bathrooms: 2, m2Total: 240, m2Cubiertos: 155, garage: true, featured: false, description: 'Casa en Barrio La Barraca, Guaymallén. Amplios ambientes, jardín, cochera. Muy buen estado. Zona en constante crecimiento y revalorización.', images: ['/properties/19/20231220_153537 - Federico Gulino.jpeg'] },
  { id: 20, title: 'Casa Barrio Teresa de los Andes', address: 'Barrio Teresa de los Andes, Guaymallén', zone: 'Guaymallén', type: 'Casa', operation: 'Venta', price: 125000, currency: 'USD', bedrooms: 3, bathrooms: 2, m2Total: 270, m2Cubiertos: 165, garage: true, featured: false, description: 'Preciosa casa en barrio residencial Teresa de los Andes. Tres dormitorios, dos baños, living comedor, cocina, galería techada y jardín. Imperdible.', images: ['/properties/20/0115feca-1bcd-4a24-8111-71af116b41f8.jpg'] },
  { id: 21, title: 'Casa Complejo Los Guindos', address: 'Complejo Los Guindos, Guaymallén', zone: 'Guaymallén', type: 'Casa', operation: 'Venta', price: 142000, currency: 'USD', bedrooms: 3, bathrooms: 2, m2Cubiertos: 170, garage: true, featured: true, description: 'Casa en complejo cerrado Los Guindos. Seguridad privada, areas comunes con pileta y cancha. Tres dormitorios, terminaciones de primera. Excelente calidad de vida.', images: ['/properties/21/IMG-20260317-WA0093 - Paola Tomio.jpeg'] },
  { id: 22, title: 'Casa Vélez Sarsfield 2880', address: 'Vélez Sarsfield 2880, Guaymallén', zone: 'Guaymallén', type: 'Casa', operation: 'Venta', price: 95000, currency: 'USD', bedrooms: 3, bathrooms: 1, m2Total: 230, m2Cubiertos: 140, garage: false, featured: false, description: 'Casa familiar sobre calle importante de Guaymallén. Buen acceso, cerca de transporte. Tres dormitorios, patio grande. Oportunidad a buen precio.', images: ['/properties/22/0f9d271d-9f57-4d30-aebc-fab64431a518.jpg'] },
  { id: 23, title: 'Dúplex Elpidio González 2150', address: 'Elpidio González 2150, Guaymallén', zone: 'Guaymallén', type: 'Dúplex', operation: 'Venta', price: 118000, currency: 'USD', bedrooms: 3, bathrooms: 2, m2Cubiertos: 130, garage: true, featured: false, description: 'Moderno dúplex de 3 dormitorios. Living en planta baja, dormitorios en alto. Diseño contemporáneo, terminaciones de calidad. Ideal familia joven.', images: ['/properties/23/IMG-20250901-WA0015 - Paulo Ponce.jpeg'] },
  { id: 24, title: 'Dúplex Los Guindos', address: 'Los Guindos, Guaymallén', zone: 'Guaymallén', type: 'Dúplex', operation: 'Venta', price: 105000, currency: 'USD', bedrooms: 2, bathrooms: 2, m2Cubiertos: 110, garage: true, featured: false, description: 'Cómodo dúplex en complejo cerrado. Dos dormitorios, dos baños, cochera cubierta. Acceso a amenities del complejo. Seguridad 24hs.', images: [] },
  { id: 25, title: 'Lote Callejón Astorga', address: 'Callejón Astorga 5681, Guaymallén', zone: 'Guaymallén', type: 'Lote', operation: 'Venta', price: 38000, currency: 'USD', m2Total: 500, featured: false, description: 'Lote urbano de 500m² en zona consolidada de Guaymallén. Todos los servicios. Excelente oportunidad para construir o invertir en zona en crecimiento.', images: ['/properties/25/3d379e68-63cf-437d-8631-8f6cc7445906 - Lorena Gutierrez.jpeg'] },
  { id: 26, title: 'Lote Julián Barraquero - Dorrego', address: 'Julián Barraquero y Dorrego, Guaymallén', zone: 'Guaymallén', type: 'Lote', operation: 'Venta', price: 32000, currency: 'USD', m2Total: 420, featured: false, description: 'Lote en barrio residencial. Zona tranquila, servicios, buena conectividad. Ideal para construir la casa de sus sueños.', images: ['/properties/26/233713cf-5557-478f-99be-20cea84cb1f4.jpg'] },
  { id: 27, title: 'Casa Prestigie B Sur Mer', address: 'Barrio Sur Mer, Las Heras', zone: 'Las Heras', type: 'Casa', operation: 'Venta', price: 185000, currency: 'USD', bedrooms: 4, bathrooms: 3, m2Total: 400, m2Cubiertos: 230, garage: true, featured: true, description: 'Imponente casa de categoría en Barrio Sur Mer. Cuatro dormitorios, tres baños, pileta, quincho y jardín parquizado. La mejor propuesta de Las Heras.', images: ['/properties/27/01c73c2d-2e90-4d4d-a52f-a663ab6b7dfd.jpg'] },
  { id: 28, title: 'Lote Barrio Villa Catalina', address: 'Barrio Villa Catalina, Las Heras', zone: 'Las Heras', type: 'Lote', operation: 'Venta', price: 28000, currency: 'USD', m2Total: 400, featured: false, description: 'Lote en barrio Villa Catalina, Las Heras. Zona tranquila, en crecimiento. Todos los servicios. Buena oportunidad para construir a precio accesible.', images: ['/properties/28/20251204_102013 - DPV 1982.jpeg'] },
  { id: 29, title: 'Lote La Bastilla', address: 'La Bastilla, Las Heras', zone: 'Las Heras', type: 'Lote', operation: 'Venta', price: 45000, currency: 'USD', m2Total: 600, featured: false, description: 'Amplio lote en La Bastilla. Entorno natural privilegiado, vistas a la montaña. Zona de alto potencial turístico y residencial. Servicios disponibles.', images: ['/properties/29/2f106150-a560-4947-849a-a062607f7ec1.jpg'] },
  { id: 30, title: 'Tierras de Gregorio', address: 'Tierras de Gregorio, Las Heras', zone: 'Las Heras', type: 'Lote', operation: 'Venta', price: 52000, currency: 'USD', m2Total: 700, featured: false, description: 'Magnifico lote en Tierras de Gregorio. Entorno serrano único, vistas panorámicas. Ideal para casa de campo o inversión en zona de alta demanda.', images: ['/properties/30/35e63a81-19b4-421d-af3a-0b11ebe1136f.jpg'] },
  { id: 31, title: 'Casa Lomas de Terrada', address: 'Lomas de Terrada, Luján de Cuyo', zone: 'Luján de Cuyo', type: 'Casa', operation: 'Venta', price: 195000, currency: 'USD', bedrooms: 4, bathrooms: 3, m2Total: 450, m2Cubiertos: 250, garage: true, featured: true, description: 'Suntuosa casa en Lomas de Terrada, Luján de Cuyo. 4 dormitorios, 3 baños, pileta, quincho, jardín. Barrio de categoría con todas las comodidades. Vistas a la cordillera.', images: ['/properties/31/0669a475-25c9-4b82-a2b2-1142a30757ee.jpg'] },
  { id: 32, title: 'Casa Terruños de Araoz', address: 'Terruños de Araoz 3, Luján de Cuyo', zone: 'Luján de Cuyo', type: 'Casa', operation: 'Venta', price: 155000, currency: 'USD', bedrooms: 3, bathrooms: 2, m2Total: 320, m2Cubiertos: 180, garage: true, featured: false, description: 'Acogedora casa en barrio Terruños de Araoz. Tres dormitorios, living amplio, jardín con parrilla. Entorno viñatero único. Tranquilidad y naturaleza garantizadas.', images: ['/properties/32/2db9fcb7-e118-4c63-b5cd-dfda0616bba8.jpg'] },
  { id: 33, title: 'Casa Tierras Altas Terrada', address: 'Tierras Altas Terrada 6456, Luján de Cuyo', zone: 'Luján de Cuyo', type: 'Casa', operation: 'Venta', price: 210000, currency: 'USD', bedrooms: 4, bathrooms: 3, m2Total: 500, m2Cubiertos: 280, garage: true, featured: false, description: 'Exclusiva casa en Tierras Altas. Diseño arquitectónico único, materiales de primera. Vista a los viñedos y la cordillera. El máximo lujo en Luján de Cuyo.', images: ['/properties/33/003233AA-C688-4565-A100-B783C310A164.jpg'] },
  { id: 34, title: 'Lote Barrio La Quebrada', address: 'Barrio La Quebrada, Luján de Cuyo', zone: 'Luján de Cuyo', type: 'Lote', operation: 'Venta', price: 75000, currency: 'USD', m2Total: 900, featured: false, description: 'Excepcional lote en Barrio La Quebrada. Rodeado de naturaleza, vistas a la cordillera. Zona premium de Luján de Cuyo. Ideal para construir la casa de ensueño.', images: ['/properties/34/1a6e3d8a-d609-4ced-8675-978d067e288e.jpg'] },
  { id: 35, title: 'Lote Barrio Penta Luján', address: 'Barrio Penta, Luján de Cuyo', zone: 'Luján de Cuyo', type: 'Lote', operation: 'Venta', price: 58000, currency: 'USD', m2Total: 750, featured: false, description: 'Lote en barrio privado Penta Luján. Seguridad 24hs, calles pavimentadas, luminarias, áreas verdes. Todo el confort de un barrio cerrado premium.', images: ['/properties/35/056f4da8-ebba-4737-8ff5-cf7232984c58.jpg'] },
  { id: 36, title: 'PH Vista Oliva 115', address: 'PH Vista Oliva 115, Maipú', zone: 'Maipú', type: 'PH', operation: 'Venta', price: 132000, currency: 'USD', bedrooms: 3, bathrooms: 2, m2Cubiertos: 155, garage: true, featured: true, description: 'Lujoso PH en complejo Vista Oliva, Maipú. Terminaciones premium, cocina gourmet, terraza privada con parrilla. Entorno viñatero. La mejor propuesta de Maipú.', images: ['/properties/36/091093a1-d621-474e-aa13-0d92d36b749e.jpg'] },
  { id: 37, title: 'PH Vista Oliva 130', address: 'PH Vista Oliva 130, Maipú', zone: 'Maipú', type: 'PH', operation: 'Venta', price: 140000, currency: 'USD', bedrooms: 3, bathrooms: 2, m2Cubiertos: 165, garage: true, featured: false, description: 'Impecable PH en Vista Oliva. Living comedor con patio privado, dormitorio principal en suite. Complejo con pileta y jardines. Rodéese de viñedos.', images: ['/properties/37/05391971-d744-407c-a614-c0b338e8b01a.jpg'] },
  { id: 38, title: 'Casa Pinar del Sol 3', address: 'Pinar del Sol 3, Maipú', zone: 'Maipú', type: 'Casa', operation: 'Venta', price: 118000, currency: 'USD', bedrooms: 3, bathrooms: 2, m2Total: 280, m2Cubiertos: 160, garage: true, featured: false, description: 'Acogedora casa en barrio Pinar del Sol. Amplios espacios verdes, cochera doble, galería techada. Excelente para vivir o veranear en Maipú.', images: ['/properties/38/053159ee-a595-49b7-bb99-05f05e2043b5.jpg'] },
  { id: 39, title: 'Finca Julio A. Roca', address: 'Julio A. Roca, Maipú', zone: 'Maipú', type: 'Finca', operation: 'Venta', price: 320000, currency: 'USD', m2Total: 15000, featured: true, description: 'Excelente finca productiva en Maipú. Viñedos en producción, bodega equipada, casa de campo. Gran oportunidad de inversión vitivinícola en corazón de Maipú.', images: ['/properties/39/Screenshot_20260209_113122_WhatsApp - Federico Gulino.jpeg'] },
  { id: 40, title: 'Lote Barrio El Bosque', address: 'Barrio El Bosque, Maipú', zone: 'Maipú', type: 'Lote', operation: 'Venta', price: 42000, currency: 'USD', m2Total: 550, featured: false, description: 'Lote en barrio El Bosque, Maipú. Rodeado de arboleda, zona tranquila. Todos los servicios. Ideal para construir en un entorno natural privilegiado.', images: ['/properties/40/3996eda7-4cdc-4f4c-90a1-2c797146f438 - Lorena Gutierrez.jpeg'] },
  { id: 41, title: 'Casa Barrio Quintas', address: 'Barrio Quintas, El Challao', zone: 'El Challao', type: 'Casa', operation: 'Venta', price: 88000, currency: 'USD', bedrooms: 3, bathrooms: 2, m2Total: 500, m2Cubiertos: 145, garage: true, featured: false, description: 'Casa con amplio terreno en Barrio Quintas, El Challao. Entorno serrano, mucho verde. Tres dormitorios, cochera, parrilla. Ideal para amantes de la naturaleza.', images: ['/properties/41/0612e059-6682-468f-bc2a-bef898445ad3.jpg'] },
  { id: 42, title: 'Casa Nuevas Quintas El Challao', address: 'Nuevas Quintas, El Challao', zone: 'El Challao', type: 'Casa', operation: 'Venta', price: 95000, currency: 'USD', bedrooms: 3, bathrooms: 2, m2Total: 600, m2Cubiertos: 155, garage: true, featured: false, description: 'Hermosa casa en Nuevas Quintas. Terreno de 600m² con jardín productivo, parrilla, galería. Entorno montañoso único. A minutos del centro de Mendoza.', images: ['/properties/42/baño nuev 5 - David Ponce Vaccarino.jpg'] },
  { id: 43, title: 'Deptos en Pozo Alta Mendoza', address: 'Alta Mendoza, El Challao', zone: 'El Challao', type: 'Departamento', operation: 'Venta', price: 62000, currency: 'USD', bedrooms: 2, bathrooms: 1, m2Cubiertos: 60, featured: false, description: 'Departamentos en pozo en el exclusivo barrio Alta Mendoza. Entrega programada. Terminaciones de primera, vistas a la montaña. Excelente inversión.', images: ['/properties/43/19fa4aa2-f8cb-4517-90f3-25bdda01791c.jpg'] },
  { id: 44, title: 'Lote Barrio Estancia Romero', address: 'Barrio Estancia Romero, El Challao', zone: 'El Challao', type: 'Lote', operation: 'Venta', price: 55000, currency: 'USD', m2Total: 800, featured: false, description: 'Lote en barrio privado Estancia Romero. Entorno serrano espectacular, acceso controlado, servicios. La tranquilidad del campo a minutos de la ciudad.', images: ['/properties/44/3cae60a6-f54e-40ed-8376-6ad074b807e2.jpg'] },
  { id: 45, title: 'Casa Altos la Consulta', address: 'Barrio Privado Altos la Consulta, San Carlos', zone: 'San Carlos', type: 'Casa', operation: 'Venta', price: 235000, currency: 'USD', bedrooms: 4, bathrooms: 3, m2Total: 520, m2Cubiertos: 260, garage: true, featured: true, description: 'Exclusiva casa en barrio privado Altos la Consulta, Valle de Uco. Diseño de autor, materiales de primera, vistas espectaculares a la cordillera y viñedos. Lujo absoluto.', images: ['/properties/45/003bae91-2ed5-4e42-811b-bd87befdf08e.jpg'] },
  { id: 46, title: 'Lote Altos la Consulta 1A', address: 'Altos la Consulta 1A, San Carlos', zone: 'San Carlos', type: 'Lote', operation: 'Venta', price: 85000, currency: 'USD', m2Total: 1200, featured: false, description: 'Privilegiado lote en el Valle de Uco. Vistas a la cordillera nevada y viñedos. Barrio privado con seguridad. La inversión más exclusiva de Mendoza.', images: ['/properties/46/04db592c-dffc-4b90-aaa7-e7afa7fbc022.jpg'] },
  { id: 47, title: 'Lote Altos la Consulta 5B', address: 'Altos la Consulta 5B, San Carlos', zone: 'San Carlos', type: 'Lote', operation: 'Venta', price: 92000, currency: 'USD', m2Total: 1500, featured: false, description: 'Amplio lote con vista panorámica en Altos la Consulta. El Valle de Uco en todo su esplendor. Zona de altísima valorización. Una inversión segura y rentable.', images: ['/properties/47/04db592c-dffc-4b90-aaa7-e7afa7fbc022.jpg'] },
  { id: 48, title: 'Finca Talavera', address: 'Finca Talavera, San Martín', zone: 'San Martín', type: 'Finca', operation: 'Venta', price: 480000, currency: 'USD', m2Total: 80000, featured: true, description: 'Gran finca en el Este mendocino. Viñedos varietales en producción, olivares, bodega y casa patronal. Oportunidad única para inversión agroindustrial en zona de alta productividad.', images: ['/properties/48/05c06c6b-44b7-4820-921b-140440a613c5.jpg'] },
  { id: 49, title: 'Finca 14 Has Santa Rosa', address: 'Santa Rosa, Mendoza', zone: 'Santa Rosa', type: 'Finca', operation: 'Venta', price: 280000, currency: 'USD', m2Total: 140000, featured: false, description: 'Finca de 14 hectáreas en Santa Rosa. Tierra de primera calidad, riego por goteo, producción mixta. Ideal para ampliar actividad agrícola o invertir en el campo mendocino.', images: ['/properties/49/22eec713-5a0f-4fb9-82b4-e05949cc18e9.jpg'] },
  { id: 50, title: 'Finca Guinazú 39 Ha', address: 'Calle Guinazú, Santa Rosa', zone: 'Santa Rosa', type: 'Finca', operation: 'Venta', price: 650000, currency: 'USD', m2Total: 390000, featured: true, description: 'Excelente oportunidad: 39 hectáreas productivas en Santa Rosa. Viñedos, olivares y zona de producción hortícola. Casa patronal, galpones y depósito incluidos.', images: ['/properties/50/0e7e3775-c956-4975-a928-2c8562cfdf5f.jpg'] },
];

function toPropertyData(p: Property): propertyData {
  const category = categoryMap[p.type];
  const livingArea = p.m2Cubiertos
    ? `${p.m2Cubiertos}m²`
    : p.m2Total
      ? `${p.m2Total}m²`
      : '-';

  return {
    id: String(p.id),
    property_img: p.images[0] || '/images/properties/prop-1.jpg',
    property_title: p.title,
    property_price: formatPrice(p.price, p.currency),
    category,
    category_img: categoryImgMap[category],
    rooms: (p.bedrooms ?? 0) + (p.bathrooms ?? 0),
    bathrooms: p.bathrooms ?? 0,
    location: p.zone,
    livingArea,
    tag: p.operation === 'Venta' ? 'Sell' : 'Rent',
    check: p.featured,
    status: p.operation === 'Venta' ? 'Buy' : 'Rent',
    type: p.type,
    beds: p.bedrooms ?? 0,
    garages: p.garage ? 1 : 0,
    region: p.zone,
    name: p.title,
    slug: toSlug(p.title),
  };
}

export async function GET() {
  return NextResponse.json(modicaProperties.map(toPropertyData));
}
